mode: high_fidelity
pretrained_weight: null
type: VanillaGates
op_type: LOOSE_END_PRIMITIVES
mode: high_fidelity
dropout: 0.5
loss_type: mse
gates_concat: old_predictor
dataset_mode: acc_adv_surrogate